// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfTB6sNZye8ZQ3us6qtC2jt8HfFvaNG_A',
    appId: '1:316360685149:web:6f7a39c813f884f48fffb4',
    messagingSenderId: '316360685149',
    projectId: 'doctor-s-desk-6c762',
    authDomain: 'doctor-s-desk-6c762.firebaseapp.com',
    storageBucket: 'doctor-s-desk-6c762.appspot.com',
    measurementId: 'G-F5MKTK32S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqEVR8reuRhlPgD4BxzntkYKtGZlPD98',
    appId: '1:316360685149:android:4d7384b85bced5d48fffb4',
    messagingSenderId: '316360685149',
    projectId: 'doctor-s-desk-6c762',
    storageBucket: 'doctor-s-desk-6c762.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoBh69SIkUjW5um1sNZtt5lypAl__FXBM',
    appId: '1:316360685149:ios:420a541099f2c4b48fffb4',
    messagingSenderId: '316360685149',
    projectId: 'doctor-s-desk-6c762',
    storageBucket: 'doctor-s-desk-6c762.appspot.com',
    iosBundleId: 'com.example.analyzebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoBh69SIkUjW5um1sNZtt5lypAl__FXBM',
    appId: '1:316360685149:ios:420a541099f2c4b48fffb4',
    messagingSenderId: '316360685149',
    projectId: 'doctor-s-desk-6c762',
    storageBucket: 'doctor-s-desk-6c762.appspot.com',
    iosBundleId: 'com.example.analyzebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfTB6sNZye8ZQ3us6qtC2jt8HfFvaNG_A',
    appId: '1:316360685149:web:fd5abb5dd927152d8fffb4',
    messagingSenderId: '316360685149',
    projectId: 'doctor-s-desk-6c762',
    authDomain: 'doctor-s-desk-6c762.firebaseapp.com',
    storageBucket: 'doctor-s-desk-6c762.appspot.com',
    measurementId: 'G-EPRXPYZMKW',
  );
}
